/*
This file is part of Volantis Mobility Server. 

Volantis Mobility Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Volantis Mobility Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Volantis Mobility Server.  If not, see <http://www.gnu.org/licenses/>. 
*/
/* ----------------------------------------------------------------------------
 * This code was automatically generated by PropertyValueLookupUtilities
 * on 3/14/08 7:12 PM
 *
 * YOU MUST NOT MODIFY THIS FILE
 * ----------------------------------------------------------------------------
 */

package com.volantis.mcs.assets;

import java.util.HashMap;
import java.util.Map;

public class ScriptAssetUtilities {

  /**
   * An array of the allowable values for the script asset
   * programmingLanguage.
   */
  private static Object [] programmingLanguageArray;

  /**
   * An array of the allowable values for the script asset mimeType.
   */
  private static Object [] mimeTypeArray;

  /**
   * An array of the allowable values for the script asset valueType.
   */
  private static Object [] valueTypeArray;

  /**
   * A bidirectional map between internal and external representations of the
   * script asset valueType.
   */
  private static Map valueTypeMap;

  static {
    Object internal;
    String external;

    programmingLanguageArray = new String [] {
      ScriptAsset.JAVA_SCRIPT,
      ScriptAsset.JAVA_SCRIPT_1_0,
      ScriptAsset.JAVA_SCRIPT_1_1,
      ScriptAsset.JAVA_SCRIPT_1_2,
      ScriptAsset.JAVA_SCRIPT_1_3,
      ScriptAsset.JAVA_SCRIPT_1_4,
      ScriptAsset.WML_TASK,
    };

    mimeTypeArray = new String [] {
      "text/javascript",
      "application/x-javascript",
      "text/vnd.wap.wml",
    };

    valueTypeArray = new Integer [] {
      new Integer (ScriptAsset.URL),
      new Integer (ScriptAsset.LITERAL),
    };

    valueTypeMap = new HashMap ();

    external = "url";
    valueTypeMap.put (valueTypeArray [0], external);
    valueTypeMap.put (external, valueTypeArray [0]);

    external = "literal";
    valueTypeMap.put (valueTypeArray [1], external);
    valueTypeMap.put (external, valueTypeArray [1]);
  }

  public static Object [] getProgrammingLanguageArray () {
    return programmingLanguageArray;
  }

  public static Object [] getMimeTypeArray () {
    return mimeTypeArray;
  }

  public static Object [] getValueTypeArray () {
    return valueTypeArray;
  }

  public static Map getValueTypeMap () {
    return valueTypeMap;
  }
}
