/*
This file is part of Volantis Mobility Server. 

Volantis Mobility Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Volantis Mobility Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Volantis Mobility Server.  If not, see <http://www.gnu.org/licenses/>. 
*/
/* ----------------------------------------------------------------------------
 * (c) Copyright Volantis Systems Ltd. 2007. 
 * ----------------------------------------------------------------------------
 */
package com.volantis.synergetics.descriptorstore;

import java.util.Date;

/**
 * A generated Item is contains a number of parameters and a unique external
 * ID. Two items are the same as each other if they have the same configuration
 * parameters. They are equal if all parameters and parameterNames are equal.
 *
 * <p>
 * <strong>Warning: This is a facade provided for use by user code, not for
 * implementation by user code. User implementations of this interface are
 * highly likely to be incompatible with future releases of the product at both
 * binary and source levels. </strong>
 * </p>
 */
public interface ResourceDescriptor {

    /**
     * Return the external unique ID.
     *
     * @return the external unique ID
     */
    public String getExternalID();

    /**
     * Set the external unique ID.
     *
     * @param externalID the external unique ID
     */
    public void setExternalID(String externalID);

    /**
     * Return the type of the resource descriptor
     * 
     * @return the type of the resource descriptor
     */
    public String getResourceType();

    /**
     * Return the last access time of the generated item. This is the last
     * time it was accessed.
     *
     * @return the last access time of the generated item.
     */
    public Date getLastAccess();

    /**
     * Return the date that the item was last generated on. This can be
     * considered the creation date of the item in most circumstances
     *
     * @return the date that the item was last generated on
     */
    public Date getLastGenerated();

    /**
     * Return the parameters that were initially set on the item
     * @return the parameters that were initially set on the item
     */
    public Parameters getInputParameters();

    /**
     * Return the parameters that have been generated by internal processing
     *
     * @return the parameters that have been generated by internal processing
     */
    public Parameters getOutputParameters();


    /**
     * Return the set of parameter names that have been requested.
     *
     * @return the set of parameter names that have been requested.
     */
    public ParameterNames getRequestedParameterNames();

    /**
     * Return the time to live in seconds.
     *
     * @return the time to live in seconds.
     */
    public long getTimeToLive();

    /**
     * Set the time to live in seconds.
     *
     * @param timeToLive the time to live in seconds.
     */
    public void setTimeToLive(long timeToLive);

}
