rem ---------------------------------------------------------------------------
rem $Header: /src/voyager/db/internal/sql/drop_tables.sql,v 1.1 2001/12/27 14:51:22 jason Exp $
rem ---------------------------------------------------------------------------
rem (c) Volantis Systems Ltd 2000. 
rem ---------------------------------------------------------------------------
rem Change History:
rem
rem Date         Who             Description
rem ---------    --------------- ----------------------------------------------
rem 21-Nov-01    Payal           VBM:2001111202 - Created.
rem ---------------------------------------------------------------------------


DROP TABLE ASSETGROUP CASCADE CONSTRAINTS ; 

DROP TABLE AUDIOASSET CASCADE CONSTRAINTS ;

DROP TABLE AUDIOCOMPONENT CASCADE CONSTRAINTS ; 

DROP TABLE BRPLUGIN_ATTRS CASCADE CONSTRAINTS ; 

DROP TABLE BUTTONIMAGECOMPONENT CASCADE CONSTRAINTS ; 

DROP TABLE CHARTASSET CASCADE CONSTRAINT;

DROP TABLE CHARTCOMPONENT CASCADE CONSTRAINTS ; 

DROP TABLE DEVICEIMAGEASSET CASCADE CONSTRAINTS ; 

DROP TABLE DEVICE_LAYOUTS CASCADE CONSTRAINTS ; 

DROP TABLE DEVICE_PATTERNS CASCADE CONSTRAINTS ; 

DROP TABLE DYNAMICVISUALASSET CASCADE CONSTRAINTS ; 

DROP TABLE DYNAMICVISUALCOMPONENT CASCADE CONSTRAINTS ;

DROP TABLE ESCAPECOMPONENT CASCADE CONSTRAINTS ; 

DROP TABLE EXTERNALREPOSITORYDEFINITION CASCADE CONSTRAINTS ; 

DROP TABLE FORMAT_ATTRIBUTES CASCADE CONSTRAINTS ; 

DROP TABLE GENERICIMAGEASSET CASCADE CONSTRAINTS ; 

DROP TABLE IMAGECOMPONENT CASCADE CONSTRAINTS ; 

DROP TABLE LAYOUTS CASCADE CONSTRAINTS ; 

DROP TABLE LAYOUT_FORMATS CASCADE CONSTRAINTS ; 

DROP TABLE LINKASSET CASCADE CONSTRAINTS ; 

DROP TABLE LINKCOMPONENT CASCADE CONSTRAINTS ; 

DROP TABLE LOCKS CASCADE CONSTRAINTS ; 

DROP TABLE LOCK_HOLDERS CASCADE CONSTRAINTS ; 

DROP TABLE POLICYPREFERENCE CASCADE CONSTRAINTS ; 

DROP TABLE POLICY_VALUES CASCADE CONSTRAINTS ; 

DROP TABLE PROPERTYEDITORS CASCADE CONSTRAINTS ; 

DROP TABLE RESOURCEBUNDLES CASCADE CONSTRAINTS ; 

DROP TABLE REVISION CASCADE CONSTRAINTS ; 

DROP TABLE ROLLOVERIMAGECOMPONENT CASCADE CONSTRAINTS ; 

DROP TABLE SCRIPTCOMPONENT CASCADE CONSTRAINTS ; 

DROP TABLE SMARTLINK CASCADE CONSTRAINTS ; 

DROP TABLE STYLES CASCADE CONSTRAINTS ; 

DROP TABLE TEXTASSET CASCADE CONSTRAINTS ; 

DROP TABLE TEXTCOMPONENT CASCADE CONSTRAINTS ; 

DROP TABLE TEXTIMG CASCADE CONSTRAINTS ;

DROP TABLE THEMES CASCADE CONSTRAINTS ;

DROP TABLE USERINFORMATION CASCADE CONSTRAINTS ; 

DROP TABLE VOLANTIS_TABS CASCADE CONSTRAINTS ; 

REM
REM ===========================================================================
REM Change History
REM ===========================================================================
REM $Log$

REM 06-Oct-04	5710/1	geoff	VBM:2004052005 Short column name support

REM ===========================================================================
REM
