

ALTER TABLE VMAUDIOCOMPONENT
ADD COLUMN TIMETOLIVE NUMERIC(5);
ALTER TABLE VMAUDIOCOMPONENT
ADD COLUMN RETRYINTERVAL NUMERIC(5);
ALTER TABLE VMAUDIOCOMPONENT
ADD COLUMN RETRYMAXCOUNT NUMERIC(5);
ALTER TABLE VMAUDIOCOMPONENT
ADD COLUMN RETAINDURINGRETRY	NUMERIC(1);
ALTER TABLE VMAUDIOCOMPONENT
ADD COLUMN RETRYFAILEDRETRIEVAL NUMERIC(1);
ALTER TABLE VMAUDIOCOMPONENT
ADD COLUMN CACHETHISPOLICY NUMERIC(1);

ALTER TABLE VMBUTTONIMAGECOMPONENT
ADD COLUMN TIMETOLIVE NUMERIC(5);
ALTER TABLE VMBUTTONIMAGECOMPONENT
ADD COLUMN RETRYINTERVAL NUMERIC(5);
ALTER TABLE VMBUTTONIMAGECOMPONENT
ADD COLUMN RETRYMAXCOUNT NUMERIC(5);
ALTER TABLE VMBUTTONIMAGECOMPONENT
ADD COLUMN RETAINDURINGRETRY NUMERIC(1);
ALTER TABLE VMBUTTONIMAGECOMPONENT
ADD COLUMN RETRYFAILEDRETRIEVAL NUMERIC(1);
ALTER TABLE VMBUTTONIMAGECOMPONENT
ADD COLUMN CACHETHISPOLICY NUMERIC(1);

ALTER TABLE VMCHARTCOMPONENT
ADD COLUMN TIMETOLIVE NUMERIC(5);
ALTER TABLE VMCHARTCOMPONENT
ADD COLUMN RETRYINTERVAL NUMERIC(5);
ALTER TABLE VMCHARTCOMPONENT
ADD COLUMN RETRYMAXCOUNT NUMERIC(5);
ALTER TABLE VMCHARTCOMPONENT
ADD COLUMN RETAINDURINGRETRY NUMERIC(1);
ALTER TABLE VMCHARTCOMPONENT
ADD COLUMN RETRYFAILEDRETRIEVAL NUMERIC(1);
ALTER TABLE VMCHARTCOMPONENT
ADD COLUMN CACHETHISPOLICY NUMERIC(1);

ALTER TABLE VMDYNAMICVISUALCOMPONENT
ADD COLUMN TIMETOLIVE NUMERIC(5);
ALTER TABLE VMDYNAMICVISUALCOMPONENT
ADD COLUMN RETRYINTERVAL NUMERIC(5);
ALTER TABLE VMDYNAMICVISUALCOMPONENT
ADD COLUMN RETRYMAXCOUNT NUMERIC(5);
ALTER TABLE VMDYNAMICVISUALCOMPONENT
ADD COLUMN RETAINDURINGRETRY NUMERIC(1);
ALTER TABLE VMDYNAMICVISUALCOMPONENT
ADD COLUMN RETRYFAILEDRETRIEVAL NUMERIC(1);
ALTER TABLE VMDYNAMICVISUALCOMPONENT
ADD COLUMN CACHETHISPOLICY NUMERIC(1);

ALTER TABLE VMIMAGECOMPONENT
ADD COLUMN TIMETOLIVE NUMERIC(5);
ALTER TABLE VMIMAGECOMPONENT
ADD COLUMN RETRYINTERVAL NUMERIC(5);
ALTER TABLE VMIMAGECOMPONENT
ADD COLUMN RETRYMAXCOUNT NUMERIC(5);
ALTER TABLE VMIMAGECOMPONENT
ADD COLUMN RETAINDURINGRETRY NUMERIC(1);
ALTER TABLE VMIMAGECOMPONENT
ADD COLUMN RETRYFAILEDRETRIEVAL NUMERIC(1);
ALTER TABLE VMIMAGECOMPONENT
ADD COLUMN CACHETHISPOLICY NUMERIC(1);

ALTER TABLE VMLINKCOMPONENT
ADD COLUMN TIMETOLIVE NUMERIC(5);
ALTER TABLE VMLINKCOMPONENT
ADD COLUMN RETRYINTERVAL NUMERIC(5);
ALTER TABLE VMLINKCOMPONENT
ADD COLUMN RETRYMAXCOUNT NUMERIC(5);
ALTER TABLE VMLINKCOMPONENT
ADD COLUMN RETAINDURINGRETRY NUMERIC(1);
ALTER TABLE VMLINKCOMPONENT
ADD COLUMN RETRYFAILEDRETRIEVAL NUMERIC(1);
ALTER TABLE VMLINKCOMPONENT
ADD COLUMN CACHETHISPOLICY NUMERIC(1);

ALTER TABLE VMROLLOVERIMAGECOMPONENT
ADD COLUMN TIMETOLIVE NUMERIC(5);
ALTER TABLE VMROLLOVERIMAGECOMPONENT
ADD COLUMN RETRYINTERVAL NUMERIC(5);
ALTER TABLE VMROLLOVERIMAGECOMPONENT
ADD COLUMN RETRYMAXCOUNT NUMERIC(5);
ALTER TABLE VMROLLOVERIMAGECOMPONENT
ADD COLUMN RETAINDURINGRETRY NUMERIC(1);
ALTER TABLE VMROLLOVERIMAGECOMPONENT
ADD COLUMN RETRYFAILEDRETRIEVAL NUMERIC(1);
ALTER TABLE VMROLLOVERIMAGECOMPONENT
ADD COLUMN CACHETHISPOLICY NUMERIC(1);

ALTER TABLE VMSCRIPTCOMPONENT
ADD COLUMN TIMETOLIVE NUMERIC(5);
ALTER TABLE VMSCRIPTCOMPONENT
ADD COLUMN RETRYINTERVAL NUMERIC(5);
ALTER TABLE VMSCRIPTCOMPONENT
ADD COLUMN RETRYMAXCOUNT NUMERIC(5);
ALTER TABLE VMSCRIPTCOMPONENT
ADD COLUMN RETAINDURINGRETRY NUMERIC(1);
ALTER TABLE VMSCRIPTCOMPONENT
ADD COLUMN RETRYFAILEDRETRIEVAL NUMERIC(1);
ALTER TABLE VMSCRIPTCOMPONENT
ADD COLUMN CACHETHISPOLICY NUMERIC(1);

ALTER TABLE VMTEXTCOMPONENT
ADD COLUMN TIMETOLIVE NUMERIC(5);
ALTER TABLE VMTEXTCOMPONENT
ADD COLUMN RETRYINTERVAL NUMERIC(5);
ALTER TABLE VMTEXTCOMPONENT
ADD COLUMN RETRYMAXCOUNT NUMERIC(5);
ALTER TABLE VMTEXTCOMPONENT
ADD COLUMN RETAINDURINGRETRY NUMERIC(1);
ALTER TABLE VMTEXTCOMPONENT
ADD COLUMN RETRYFAILEDRETRIEVAL NUMERIC(1);
ALTER TABLE VMTEXTCOMPONENT
ADD COLUMN CACHETHISPOLICY NUMERIC(1);

ALTER TABLE VMASSETGROUP
ADD COLUMN TIMETOLIVE NUMERIC(5);
ALTER TABLE VMASSETGROUP
ADD COLUMN RETRYINTERVAL NUMERIC(5);
ALTER TABLE VMASSETGROUP
ADD COLUMN RETRYMAXCOUNT NUMERIC(5);
ALTER TABLE VMASSETGROUP
ADD COLUMN RETAINDURINGRETRY NUMERIC(1);
ALTER TABLE VMASSETGROUP
ADD COLUMN RETRYFAILEDRETRIEVAL NUMERIC(1);
ALTER TABLE VMASSETGROUP
ADD COLUMN CACHETHISPOLICY NUMERIC(1);

ALTER TABLE VMTHEME
ADD COLUMN TIMETOLIVE NUMERIC(5);
ALTER TABLE VMTHEME
ADD COLUMN RETRYINTERVAL NUMERIC(5);
ALTER TABLE VMTHEME
ADD COLUMN RETRYMAXCOUNT NUMERIC(5);
ALTER TABLE VMTHEME
ADD COLUMN RETAINDURINGRETRY NUMERIC(1);
ALTER TABLE VMTHEME
ADD COLUMN RETRYFAILEDRETRIEVAL NUMERIC(1);
ALTER TABLE VMTHEME
ADD COLUMN CACHETHISPOLICY NUMERIC(1);

ALTER TABLE VMDEVICE_LAYOUTS
ADD COLUMN TIMETOLIVE NUMERIC(5);
ALTER TABLE VMDEVICE_LAYOUTS
ADD COLUMN RETRYINTERVAL NUMERIC(5);
ALTER TABLE VMDEVICE_LAYOUTS
ADD COLUMN RETRYMAXCOUNT NUMERIC(5);
ALTER TABLE VMDEVICE_LAYOUTS
ADD COLUMN RETAINDURINGRETRY NUMERIC(1);
ALTER TABLE VMDEVICE_LAYOUTS
ADD COLUMN RETRYFAILEDRETRIEVAL NUMERIC(1);
ALTER TABLE VMDEVICE_LAYOUTS
ADD COLUMN CACHETHISPOLICY NUMERIC(1);
