/*
This file is part of Volantis Mobility Server. 

Volantis Mobility Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Volantis Mobility Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Volantis Mobility Server.  If not, see <http://www.gnu.org/licenses/>. 
*/
/* ----------------------------------------------------------------------------
 * $Header: /src/voyager/testsuite/unit/com/volantis/UnitTestConstants.java,v 1.1 2003/02/21 17:56:20 aboyd Exp $
 * ----------------------------------------------------------------------------
 * (c) Volantis Systems Ltd 2002. 
 * ----------------------------------------------------------------------------
 * Change History:
 *
 * Date         Who             Description
 * ---------    --------------- -----------------------------------------------
 * 21-Feb-03    Allan           VBM:2003021803 - Class for general constants 
 *                              for use by unit test cases. 
 * ----------------------------------------------------------------------------
 */
package com.volantis.mcs.layouts;

/**
 * A class containing constants for use by Unit tests.
 */ 
public final class UnitTestConstants {
    
//    /**
//     * The acceptable probability of an implementation of hashCode() providing
//     * different results for different objects. Note that this constant is
//     * really used to check that nothing stupid has happened to hashCode()
//     * implementations rather than to say that 1/1000 objects is an ok
//     * level for duplicate hashcodes on different objects. Raising this
//     * value much higher (which would be more realistic) will cause some
//     * testcases to take a very long time (and indeed 1000 is too high for
//     * some in this respect in which case a specific value has been used).
//     * Error messages generated by tests that fail using this constant should
//     * specify the constant in the message.
//     */
//    public static final int HASHCODE_ACCEPTABILITY_CONSTANT = 1000;
}

/*
 ===========================================================================
 Change History
 ===========================================================================
 $Log$

 11-Jul-05	8992/1	pduffin	VBM:2005071109 Modified layouts and formats to allow separation between runtime and design time classes

 08-Dec-04	6416/3	ianw	VBM:2004120703 New Build

 08-Dec-04	6416/1	ianw	VBM:2004120703 New Build

 ===========================================================================
*/
