/*
This file is part of Volantis Mobility Server. 

Volantis Mobility Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Volantis Mobility Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Volantis Mobility Server.  If not, see <http://www.gnu.org/licenses/>. 
*/
/* ----------------------------------------------------------------------------
 * (c) Volantis Systems Ltd 2003. 
 * ----------------------------------------------------------------------------
 */
package com.volantis.mcs.protocols.dissection;

import com.volantis.mcs.dom.Element;
import com.volantis.mcs.protocols.DOMOutputBuffer;
import com.volantis.mcs.protocols.OutputBuffer;
import com.volantis.mcs.protocols.menu.model.Menu;
import com.volantis.mcs.protocols.menu.shared.renderer.MenuBracketingRenderer;
import com.volantis.mcs.protocols.renderer.RendererException;

/**
 * A delgating menu bracketing renderer which adds the SHARD LINK GROUP markup
 * to that markup generated by the contained menu bracketing renderer.
 */
public final class ShardLinkMenuBracketingRenderer
        implements MenuBracketingRenderer {

    /**
     * The copyright statement.
     */
    private static final String mark = "(c) Volantis Systems Ltd 2004.";

    /**
     * The menu bracketing renderer that we delegate to.
     */
    private final MenuBracketingRenderer delegate;

    /**
     * Construct an instance of this class.
     *
     * @param delegate the menu bracketing renderer we delegate to.
     */
    public ShardLinkMenuBracketingRenderer(MenuBracketingRenderer delegate) {
        this.delegate = delegate;
    }

    /**
     * Start a SHARD LINK GROUP element and then open our delegate.
     */
    // Other javadoc inherited.
    public void open(OutputBuffer buffer, Menu menu)
            throws RendererException {

        DOMOutputBuffer dom = (DOMOutputBuffer) buffer;

        // Downcast to the shard link specific menu so we can extract the
        // shard link group attributes we prepared earlier.
        ShardLinkMenu shardLinkMenu = (ShardLinkMenu) menu;

        // Open the SHARD LINK GROUP element.
        Element shardLinkGroup = dom.openElement(
                DissectionConstants.SHARD_LINK_GROUP_ELEMENT);

        // Add the shard link group attributes we prepared earlier.
        shardLinkGroup.setAnnotation(
                shardLinkMenu.getShardLinkGroupAttributes());

        delegate.open(buffer, menu);
    }

    /**
     * Close our delegate and then and end the SHARD LINK GROUP element.
     */
    // Other javadoc inherited.
    public void close(OutputBuffer buffer, Menu menu)
            throws RendererException {

        delegate.close(buffer, menu);

        DOMOutputBuffer dom = (DOMOutputBuffer) buffer;

        // Close the SHARD LINK GROUP element.
        dom.closeElement(DissectionConstants.SHARD_LINK_GROUP_ELEMENT);
    }

}

/*
 ===========================================================================
 Change History
 ===========================================================================
 $Log$

 11-Mar-05	7357/2	pcameron	VBM:2005030906 Fixed node annotation for dissection

 08-Dec-04	6416/3	ianw	VBM:2004120703 New Build

 08-Dec-04	6416/1	ianw	VBM:2004120703 New Build

 13-May-04	4315/3	geoff	VBM:2004051204 Enhance Menu Support: WML Dissection: Integration

 13-May-04	4315/1	geoff	VBM:2004051204 Enhance Menu Support: WML Dissection: Integration

 ===========================================================================
*/
