/* ----------------------------------------------------------------------------
 * (c) Volantis Systems Ltd 2004. All Rights Reserved.
 * ----------------------------------------------------------------------------
 */

package com.volantis.testtools.mock.impl;

import junit.framework.Assert;

import com.volantis.testtools.mock.Event;

/**
 * The base of all events generated by mock objects.
 */
public abstract class EventImpl implements Event {

    /**
     * The source of the event, e.g. the object that triggered the event.
     */
    private Object source;

    /**
     * Initialise.
     * @param source The source of the event, may not be null.
     */
    protected EventImpl(Object source) {
        Assert.assertNotNull(source);
        this.source = source;
    }

    public Object getSource() {
        return source;
    }
}

/*
 ===========================================================================
 Change History
 ===========================================================================
 $Log$

 20-May-05	8277/1	pduffin	VBM:2005051704 Added support for automatically generating mock objects

 08-Dec-04	6416/3	ianw	VBM:2004120703 New Build

 08-Dec-04	6416/1	ianw	VBM:2004120703 New Build

 06-Apr-04	3703/1	pduffin	VBM:2004040106 Added beginnings of a mock object framework

 ===========================================================================
*/
