
INSERT INTO VMPROPERTYEDITORS (GRP, PROPERTY, ATTRIBUTE, VALUE, REVISION) VALUES (
    'devicePolicies', 'protocol', '20', 'XHTMLBasic_MIB2_0', -1 );
UPDATE VMPROPERTYEDITORS SET VALUE='21' WHERE GRP='devicePolicies' AND PROPERTY='protocol' AND ATTRIBUTE='count';

