
CREATE TABLE VMLAYOUT ( 
  NAME      VARCHAR2 (254)  NOT NULL, 
  TYPE      VARCHAR2 (32), 
  REVISION  NUMBER (9)    DEFAULT 0 ) ; 


ALTER TABLE VMLAYOUT
 ADD CONSTRAINT PK_VMLAYOUT
  PRIMARY KEY (NAME) 
; 

