INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'yellow', 0, NULL, 'vnd.wtv-y', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'select', 0, NULL, 'vnd.wtv-sel', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'red', 0, NULL, 'vnd.wtv-r', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'green', 0, NULL, 'vnd.wtv-g', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'text', 0, NULL, 'vnd.wtv-text', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'plus', 0, NULL, 'vnd.wtv-plus', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'mInus', 0, NULL, 'vnd.wtv-minus', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'one', 0, NULL, 'vnd.wtv-1', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'two', 0, NULL, 'vnd.wtv-2', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'three', 0, NULL, 'vnd.wtv-3', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'four', 0, NULL, 'vnd.wtv-4', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'five', 0, NULL, 'vnd.wtv-5', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'six', 0, NULL, 'vnd.wtv-6', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'seven', 0, NULL, 'vnd.wtv-7', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'nine', 0, NULL, 'vnd.wtv-9', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'zero', 0, NULL, 'vnd.wtv-0', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'help', 0, NULL, 'help', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'backup', 0, NULL, 'prev', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'upArrow', 0, NULL, 'vnd.wtv-up', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'downArrow', 0, NULL, 'vnd.wtv-down', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'leftArrow', 0, NULL, 'vnd.wtv-left', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'rightArrow', 0, NULL, 'vnd.wtv-right', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'info', 0, NULL, 'vnd.wtv-i', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'fastRewind', 0, NULL, '1028', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'volumePlus', 0, NULL, '1026', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'clear', 0, NULL, '1290', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'back', 0, NULL, '1288', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'Fwds', 0, NULL, '1287', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'plus', 0, NULL, '-', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'mInus', 0, NULL, '+', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'previous', 0, NULL, '*', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'info', 0, NULL, '775', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'mail', 0, NULL, '770', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'help', 0, NULL, '779', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'search', 0, NULL, '772', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'jump', 0, NULL, '1041', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'tv+', 0, NULL, '782', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'pip', 0, NULL, '1040', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'record', 0, NULL, '1034', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'mute', 0, NULL, '1036', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'stop', 0, NULL, '1035', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'recentHistory', 0, NULL, '778', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'upArrow', 0, NULL, '1280', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'fastForward', 0, NULL, '1031', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'ticker', 0, NULL, '776', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'leftArrow', 0, NULL, '1282', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'yellow', 0, NULL, '1044', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'volumeMinus', 0, NULL, '1027', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'rewind', 0, NULL, '1029', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'favorites', 0, NULL, '47', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'home', 0, NULL, '769', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'fwd', 0, NULL, '1289', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'pageUp', 0, NULL, '1284', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'power', 0, NULL, '27', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'red', 0, NULL, '1042', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'pageDown', 0, NULL, '1285', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'tab', 0, NULL, '9', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'forward', 0, NULL, '1030', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'print', 0, NULL, '781', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'play', 0, NULL, '1033', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'zoom', 0, NULL, '1037', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'downArrow', 0, NULL, '1281', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'guide', 0, NULL, '771', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'blue', 0, NULL, '1045', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'backSpace', 0, NULL, '8', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'eight', 0, NULL, 'vnd.wtv-8', 2, '-', 'WapTV', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'messenger', 0, NULL, '784', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'settings', 0, NULL, '780', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'payPerView', 0, NULL, '777', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'pause', 0, NULL, '1032', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'chat', 0, NULL, '783', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'backwards', 0, NULL, '1286', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'green', 0, NULL, '1043', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'go', 0, NULL, '785', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'enter', 0, NULL, '13', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'rightArrow', 0, NULL, '1283', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'refresh', 0, NULL, '129', 2, '-', 'Liberate-1.1', 1); 
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'blue', 0, NULL, 'vnd.wtv-b', 2, '-', 'WapTV', 1); 
commit;
INSERT INTO TEXTASSET ( NAME, REVISION, ASSETGROUPNAME, VALUE, VALUETYPE, LANGUAGE, DEVICENAME,
ENCODING ) VALUES ( 
'exit', 0, NULL, '1039', 2, '-', 'Liberate-1.1', 1); 
