
rem VBM:2002090210 - Add cache columns to cacheable components, layouts and themes

ALTER TABLE VMAUDIOCOMPONENT
ADD TIMETOLIVE NUMERIC(5)
ADD RETRYINTERVAL NUMERIC(5)
ADD RETRYMAXCOUNT NUMERIC(5)
ADD RETAINDURINGRETRY	NUMERIC(1)
ADD RETRYFAILEDRETRIEVAL NUMERIC(1)
ADD CACHETHISPOLICY NUMERIC(1);

ALTER TABLE VMBUTTONIMAGECOMPONENT
ADD TIMETOLIVE NUMERIC(5)
ADD RETRYINTERVAL NUMERIC(5)
ADD RETRYMAXCOUNT NUMERIC(5)
ADD RETAINDURINGRETRY NUMERIC(1)
ADD RETRYFAILEDRETRIEVAL NUMERIC(1)
ADD CACHETHISPOLICY NUMERIC(1);

ALTER TABLE VMCHARTCOMPONENT
ADD TIMETOLIVE NUMERIC(5)
ADD RETRYINTERVAL NUMERIC(5)
ADD RETRYMAXCOUNT NUMERIC(5)
ADD RETAINDURINGRETRY NUMERIC(1)
ADD RETRYFAILEDRETRIEVAL NUMERIC(1)
ADD CACHETHISPOLICY NUMERIC(1);

ALTER TABLE VMDYNAMICVISUALCOMPONENT
ADD TIMETOLIVE NUMERIC(5)
ADD RETRYINTERVAL NUMERIC(5)
ADD RETRYMAXCOUNT NUMERIC(5)
ADD RETAINDURINGRETRY NUMERIC(1)
ADD RETRYFAILEDRETRIEVAL NUMERIC(1)
ADD CACHETHISPOLICY NUMERIC(1);

ALTER TABLE VMIMAGECOMPONENT
ADD TIMETOLIVE NUMERIC(5)
ADD RETRYINTERVAL NUMERIC(5)
ADD RETRYMAXCOUNT NUMERIC(5)
ADD RETAINDURINGRETRY NUMERIC(1)
ADD RETRYFAILEDRETRIEVAL NUMERIC(1)
ADD CACHETHISPOLICY NUMERIC(1);

ALTER TABLE VMLINKCOMPONENT
ADD TIMETOLIVE NUMERIC(5)
ADD RETRYINTERVAL NUMERIC(5)
ADD RETRYMAXCOUNT NUMERIC(5)
ADD RETAINDURINGRETRY NUMERIC(1)
ADD RETRYFAILEDRETRIEVAL NUMERIC(1)
ADD CACHETHISPOLICY NUMERIC(1);

ALTER TABLE VMROLLOVERIMAGECOMPONENT
ADD TIMETOLIVE NUMERIC(5)
ADD RETRYINTERVAL NUMERIC(5)
ADD RETRYMAXCOUNT NUMERIC(5)
ADD RETAINDURINGRETRY NUMERIC(1)
ADD RETRYFAILEDRETRIEVAL NUMERIC(1)
ADD CACHETHISPOLICY NUMERIC(1);

ALTER TABLE VMSCRIPTCOMPONENT
ADD TIMETOLIVE NUMERIC(5)
ADD RETRYINTERVAL NUMERIC(5)
ADD RETRYMAXCOUNT NUMERIC(5)
ADD RETAINDURINGRETRY NUMERIC(1)
ADD RETRYFAILEDRETRIEVAL NUMERIC(1)
ADD CACHETHISPOLICY NUMERIC(1);

ALTER TABLE VMTEXTCOMPONENT
ADD TIMETOLIVE NUMERIC(5)
ADD RETRYINTERVAL NUMERIC(5)
ADD RETRYMAXCOUNT NUMERIC(5)
ADD RETAINDURINGRETRY NUMERIC(1)
ADD RETRYFAILEDRETRIEVAL NUMERIC(1)
ADD CACHETHISPOLICY NUMERIC(1);

ALTER TABLE VMASSETGROUP
ADD TIMETOLIVE NUMERIC(5)
ADD RETRYINTERVAL NUMERIC(5)
ADD RETRYMAXCOUNT NUMERIC(5)
ADD RETAINDURINGRETRY NUMERIC(1)
ADD RETRYFAILEDRETRIEVAL NUMERIC(1)
ADD CACHETHISPOLICY NUMERIC(1);

ALTER TABLE VMTHEME
ADD TIMETOLIVE NUMERIC(5)
ADD RETRYINTERVAL NUMERIC(5)
ADD RETRYMAXCOUNT NUMERIC(5)
ADD RETAINDURINGRETRY NUMERIC(1)
ADD RETRYFAILEDRETRIEVAL NUMERIC(1)
ADD CACHETHISPOLICY NUMERIC(1);

ALTER TABLE VMDEVICE_LAYOUTS
ADD TIMETOLIVE NUMERIC(5)
ADD RETRYINTERVAL NUMERIC(5)
ADD RETRYMAXCOUNT NUMERIC(5)
ADD RETAINDURINGRETRY NUMERIC(1)
ADD RETRYFAILEDRETRIEVAL NUMERIC(1)
ADD CACHETHISPOLICY NUMERIC(1);
