/*
This file is part of Volantis Mobility Server. 

Volantis Mobility Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Volantis Mobility Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Volantis Mobility Server.  If not, see <http://www.gnu.org/licenses/>. 
*/
/* ----------------------------------------------------------------------------
 * $Header: /src/voyager/testsuite/unit/com/volantis/mcs/protocols/html/XHTMLBasicUnabridgedTransformerTestCase.java,v 1.6 2003/04/16 10:23:22 geoff Exp $
 * ----------------------------------------------------------------------------
 * (c) Volantis Systems Ltd 2001. 
 * ----------------------------------------------------------------------------
 * Change History:
 *
 * Date         Who             Description
 * ---------    --------------- -----------------------------------------------
 * 25-Sep-02    Phil W-S        VBM:2002091901 - Created.
 * 18-Nov-02    Steve           VBM:2002111207 - Added test for transformation
 *                              of HTML generated by multiple portlet canvases
 *                              in the same region.
 * 11-Dec-02    Phil W-S        VBM:2002120212 - Added test to check that
 *                              deeply nested tables within an inverse remap
 *                              zone are correctly promoted for processing.
 * 15-Jan-03    Phil W-S        VBM:2002110402 - Rework: Updated to account for
 *                              single column table removal.
 * 17-Apr-03    Geoff           VBM:2003041505 - Commented out System.out 
 *                              calls which clutter the JUnit console output.
 * ----------------------------------------------------------------------------
 */

package com.volantis.mcs.protocols.html;

import com.volantis.mcs.devices.InternalDeviceTestHelper;
import com.volantis.mcs.devices.InternalDevice;
import com.volantis.mcs.dom.Document;
import com.volantis.mcs.dom.Element;
import com.volantis.mcs.dom.RecursingDOMVisitor;
import com.volantis.mcs.protocols.DOMProtocol;
import com.volantis.mcs.protocols.DOMTransformer;
import com.volantis.mcs.protocols.builder.ProtocolBuilder;
import com.volantis.mcs.protocols.builder.TestProtocolRegistry;
import com.volantis.mcs.protocols.trans.NullRemovingDOMTransformer;
import com.volantis.mcs.protocols.trans.TransCell;
import com.volantis.mcs.runtime.debug.StrictStyledDOMHelper;
import com.volantis.synergetics.testtools.TestCaseAbstract;

/**
 * This is the unit test for the XHTMLBasicUnabridgedTransformer and
 * UnabridgedTransformer classes.
 */
public class XHTMLBasicUnabridgedTransformerTestCase extends TestCaseAbstract {
    private StrictStyledDOMHelper helper;
    private InternalDevice internalDevice;

    /**
     * Supporting nested class used to remove erroneously inserted rowspan
     * and colspan values created by the SAX parser when in validation
     * mode.
     */
    static class RowColSpanVisitor extends RecursingDOMVisitor {

        // JavaDoc inherited
        public void visit(Element element) {
            if ("td".equals(element.getName())) {
                // Remove rowspan/colspan attributes set to the default
                // value of 1. This is a side-effect of the following
                // get* methods
                TransCell.getRowspan(element);
                TransCell.getColspan(element);
            }

            // Continue down the hierarchy
            element.forEachChild(this);
        }
    }

    protected void setUp() throws Exception {
        super.setUp();

        helper = new StrictStyledDOMHelper(null);

        internalDevice = InternalDeviceTestHelper.createTestDevice();
    }

    /**
     * All other methods are implicitly tested by this test
     */
    // This test is commentted out because it relies on an external resource
    // and as such is unreliable - currently it is preventing a commit
    // because the external resource is unavailble.
    // @todo later fix this testcase so that it does not rely on an external resource
    /*
    public void testTransform() throws Exception {
        DOMProtocol protocol = new DOMProtocol();
        XMLReader reader = DOMUtilities.getReader();
        ClassLoader loader = this.getClass().getClassLoader();
        InputStream originalFile =
            loader.getResourceAsStream(this.getClass().getName().
                                       replace('.', '/') + ".input.html");
        InputStream expectedFile =
            loader.getResourceAsStream(this.getClass().getName().
                                       replace('.', '/') + ".expected.html");

        // Enable validation to ensure that any ignorable whitespace really
        // is ignored. This has the side-effect of introducing unnecessary
        // rowspan and colspan attributes
        reader.setFeature("http://xml.org/sax/features/validation", true);

        Document dom = DOMUtilities.read(reader, originalFile);
        Document expected = DOMUtilities.read(reader, expectedFile);

        // Remove rowspan/colspan settings inserted by the parser. This happens
        // because the validation feature has been enabled
        expected.visitContents(new RowColSpanVisitor(), null);

        String domAsString;
        String expectedAsString;

        DOMTransformer transformer =
            XHTMLBasicUnabridgedTransformer.getInstance();

        // Useful debug output
        //System.out.println("Original DOM:");
        //System.out.println(DOMUtilities.toString(dom, protocol.getCharacterEncoder()));
        transformer.transform(protocol, dom);

        // Useful debug output
        //System.out.println("Transformed DOM:");
        //System.out.println(DOMUtilities.toString(dom, protocol.getCharacterEncoder()));
        domAsString = DOMUtilities.toString(dom, protocol.getCharacterEncoder());
        expectedAsString = DOMUtilities.toString(expected, protocol.getCharacterEncoder());

        assertEquals("DOM comparison failed",
                     domAsString,
                     expectedAsString);
    }
*/
    /** Tests the transformation of the HTML generated when there are multiple
     * dissecting panes in a region. Note that there is in reality no such 
     * element as 'dissectable' but since the transformer is only interested
     * in table and div elements, they should all still be removed unless the
     * div element has 'important' Styles as is the case here.
     */
    public void testMultipleDissectingPanes() throws Exception {
        ProtocolBuilder builder = new ProtocolBuilder();
        DOMProtocol protocol = (DOMProtocol) builder.build(
                new TestProtocolRegistry.TestXHTMLBasicFactory(),
                internalDevice);

        // The transformer is only interested in table and div elements so the
        // dissectable pane element can be called whatever we like, the test is
        // that it is gotten rid of by the transformer.
        String originalString =
            "<html>" +
              "<body>" +
                "<table>" +
                  "<tr><td>" +
                    "<dissectable name=\"dissecting\" path=\"region1\" " + 
                          "size=\"400\" next=\"Next\" previous=\"Previous\">" +
                      "<div style=\"background-color:blue\"><table>" +
                        "<tr><td>Create new route</td></tr>" +
                      "</table></div>" +
                    "</dissectable>" +
                  "</td></tr>" +
                "</table>" +
                "<table>" +
                  "<tr><td>" +
                    "<dissectable name=\"dissecting\" path=\"region1\" " + 
                          "size=\"400\" next=\"Next\" previous=\"Previous\">" +
                      "<div style=\"color:green\"><table>" +
                        "<tr><td>Guildford</td></tr>" +
                      "</table></div>" +
                    "</dissectable>" +
                  "</td></tr>" +
                "</table>" +
              "</body>" +
            "</html>";


        String expectedString =
            "<html>" +
              "<body>" +
                "<div style=\"background-color:blue\">Create new route</div>" +
                "<div style=\"color:green\">Guildford</div>" +
              "</body>" +
            "</html>";

        Document dom = helper.parse(originalString);
        Document expected = helper.parse(expectedString);

        DOMTransformer transformer = new XHTMLBasicUnabridgedTransformer(
                new XHTMLBasicConfiguration());

        transformer.transform(protocol, dom);

        // In actual operation this transformer would form a compound
        // transformer with the NullRemovingDOMTransformer.
        NullRemovingDOMTransformer nullRemover = new NullRemovingDOMTransformer();
        nullRemover.transform(null, dom);

        String domAsString = helper.render(dom);
        String expectedAsString = helper.render(expected);

        assertEquals("DOM comparison failed", expectedAsString, domAsString);
    }

    /**
     * Test that inverse remap does retain and process all (deeply) nested
     * tables correctly.
     *
     * @throws Exception
     */
    public void testInverseRemapTableRetention() throws Exception {
        ProtocolBuilder builder = new ProtocolBuilder();
        DOMProtocol protocol = (DOMProtocol) builder.build(
                new TestProtocolRegistry.TestXHTMLBasicFactory(),
                internalDevice);
        String original =
            "<html xmlns=\"http://www.w3.org/1999/xhtml\">" +
              "<head>" +
                "<title></title>" +
              "</head>" +
              "<body>" +
                "<table width=\"100%\">" +
                  "<tr>" +
                    "<td>" +
                      "<table>" +
                        "<tr>" +
                          "<td>" +
                            "<table>" +
                              "<tr>" +
                                "<td>" +
                                  "<table>" +
                                    "<tr>" +
                                      "<td>Main Pane</td>" +
                                    "</tr>" +
                                  "</table>" +
                                "</td>" +
                              "</tr>" +
                              "<tr>" +
                                "<td>" +
                                  "<table>" +
                                    "<tr>" +
                                      "<td>" +
                                        "<table>" +
                                          "<tr>" +
                                            "<td>C</td>" +
                                          "</tr>" +
                                        "</table>" +
                                      "</td>" +
                                      "<td>" +
                                        "<table>" +
                                          "<tr>" +
                                            "<td>B</td>" +
                                          "</tr>" +
                                        "</table>" +
                                      "</td>" +
                                    "</tr>" +
                                    "<tr>" +
                                      "<td>" +
                                        "<table>" +
                                          "<tr>" +
                                            "<td>D</td>" +
                                          "</tr>" +
                                        "</table>" +
                                      "</td>" +
                                      "<td>" +
                                        "<table>" +
                                          "<tr>" +
                                            "<td>" +
                                              "<table>" +
                                                "<tr>" +
                                                  "<td>DA</td>" +
                                                "</tr>" +
                                              "</table>" +
                                            "</td>" +
                                            "<td>" +
                                              "<table>" +
                                                "<tr>" +
                                                  "<td>DB</td>" +
                                                "</tr>" +
                                              "</table>" +
                                            "</td>" +
                                          "</tr>" +
                                          "<tr>" +
                                            "<td>" +
                                              "<table>" +
                                                "<tr>" +
                                                  "<td>DC</td>" +
                                                "</tr>" +
                                              "</table>" +
                                            "</td>" +
                                            "<td>" +
                                              "<table>" +
                                                "<tr>" +
                                                  "<td>" +
                                                    "<table>" +
                                                      "<tr>" +
                                                        "<td>DDA</td>" +
                                                      "</tr>" +
                                                    "</table>" +
                                                  "</td>" +
                                                  "<td>" +
                                                    "<table>" +
                                                      "<tr>" +
                                                        "<td>DDB</td>" +
                                                      "</tr>" +
                                                    "</table>" +
                                                  "</td>" +
                                                "</tr>" +
                                                "<tr>" +
                                                  "<td>" +
                                                    "<table>" +
                                                      "<tr>" +
                                                        "<td>DDC</td>" +
                                                      "</tr>" +
                                                    "</table>" +
                                                  "</td>" +
                                                  "<td></td>" +
                                                "</tr>" +
                                              "</table>" +
                                            "</td>" +
                                          "</tr>" +
                                        "</table>" +
                                      "</td>" +
                                    "</tr>" +
                                  "</table>" +
                                "</td>" +
                              "</tr>" +
                            "</table>" +
                          "</td>" +
                        "</tr>" +
                        "<tr>" +
                          "<td>" +
                            "<form action=\"test\" method=\"get\">" +
                              "<div>" +
                                "<input name=\"vform\" type=\"hidden\" value=\"s0\"></input>" +
                                "<table width=\"100%\">" +
                                  "<tr>" +
                                    "<td>" +
                                      "<table>" +
                                        "<tr>" +
                                          "<td>A</td>" +
                                        "</tr>" +
                                      "</table>" +
                                    "</td>" +
                                    "<td align=\"right\">" +
                                      "<table>" +
                                        "<tr>" +
                                          "<td align=\"right\">" +
                                            "<input name=\"a\" type=\"checkbox\" value=\"1\"></input>" +
                                          "</td>" +
                                        "</tr>" +
                                      "</table>" +
                                    "</td>" +
                                    "<td>" +
                                      "<table>" +
                                        "<tr>" +
                                          "<td>B</td>" +
                                        "</tr>" +
                                      "</table>" +
                                    "</td>" +
                                    "<td align=\"right\">" +
                                      "<table>" +
                                        "<tr>" +
                                          "<td align=\"right\">" +
                                            "<input name=\"b\" type=\"checkbox\" value=\"1\"></input>" +
                                          "</td>" +
                                        "</tr>" +
                                      "</table>" +
                                    "</td>" +
                                  "</tr>" +
                                  "<tr>" +
                                    "<td>" +
                                      "<table>" +
                                        "<tr>" +
                                          "<td>C</td>" +
                                        "</tr>" +
                                      "</table>" +
                                    "</td>" +
                                    "<td>" +
                                      "<table>" +
                                        "<tr>" +
                                          "<td>" +
                                            "<input name=\"c\" type=\"checkbox\" value=\"1\"></input>" +
                                          "</td>" +
                                        "</tr>" +
                                      "</table>" +
                                    "</td>" +
                                    "<td>" +
                                      "<table>" +
                                        "<tr>" +
                                          "<td>D</td>" +
                                        "</tr>" +
                                      "</table>" +
                                    "</td>" +
                                    "<td align=\"right\">" +
                                      "<table>" +
                                        "<tr>" +
                                          "<td align=\"right\">" +
                                            "<input name=\"b\" type=\"checkbox\" value=\"1\"></input>" +
                                          "</td>" +
                                        "</tr>" +
                                      "</table>" +
                                    "</td>" +
                                  "</tr>" +
                                  "<tr>" +
                                    "<td>" +
                                      "<table>" +
                                        "<tr>" +
                                          "<td>Submit</td>" +
                                        "</tr>" +
                                      "</table>" +
                                    "</td>" +
                                    "<td>" +
                                      "<table>" +
                                        "<tr>" +
                                          "<td>" +
                                            "<input title=\"Submit\" type=\"submit\" value=\"submit\"></input>" +
                                          "</td>" +
                                        "</tr>" +
                                      "</table>" +
                                    "</td>" +
                                    "<td></td>" +
                                    "<td></td>" +
                                  "</tr>" +
                                "</table>" +
                              "</div>" +
                            "</form>" +
                          "</td>" +
                        "</tr>" +
                      "</table>" +
                    "</td>" +
                  "</tr>" +
                "</table>" +
              "</body>" +
            "</html>";
        String expected =
            "<html>" +
              "<head>" +
                "<title></title>" +
              "</head>" +
              "<body>" +
                "<div>Main Pane" +
                  "<table>" +
                    "<tr>" +
                      "<td>C</td>" +
                      "<td colspan=\"3\">B</td>" +
                    "</tr>" +
                    "<tr>" +
                      "<td rowspan=\"3\">D</td>" +
                      "<td>DA</td>" +
                      "<td colspan=\"2\">DB</td>" +
                    "</tr>" +
                    "<tr>" +
                      "<td rowspan=\"2\">DC</td>" +
                      "<td>DDA</td>" +
                      "<td>DDB</td>" +
                    "</tr>" +
                    "<tr>" +
                      "<td>DDC</td>" +
                      "<td></td>" +
                    "</tr>" +
                  "</table>" +
                  "<form action=\"test\" method=\"get\">" +
                    "<div>" +
                      "<input name=\"vform\" type=\"hidden\" value=\"s0\"></input>" +
                    "</div>" +
                    "<table width=\"100%\">" +
                      "<tr>" +
                        "<td>A</td>" +
                        "<td align=\"right\">" +
                          "<input name=\"a\" type=\"checkbox\" value=\"1\"></input>" +
                        "</td>" +
                        "<td>B</td>" +
                        "<td align=\"right\">" +
                          "<input name=\"b\" type=\"checkbox\" value=\"1\"></input>" +
                        "</td>" +
                      "</tr>" +
                      "<tr>" +
                        "<td>C</td>" +
                        "<td>" +
                          "<input name=\"c\" type=\"checkbox\" value=\"1\"></input>" +
                        "</td>" +
                        "<td>D</td>" +
                        "<td align=\"right\">" +
                          "<input name=\"b\" type=\"checkbox\" value=\"1\"></input>" +
                        "</td>" +
                      "</tr>" +
                      "<tr>" +
                        "<td>Submit</td>" +
                        "<td>" +
                          "<input title=\"Submit\" type=\"submit\" value=\"submit\"></input>" +
                        "</td>" +
                        "<td></td>" +
                        "<td></td>" +
                      "</tr>" +
                    "</table>" +
                  "</form>" +
                "</div>" +
              "</body>" +
            "</html>";
        Document dom = helper.parse(original);
        Document expectedDom = helper.parse(expected);
        String domAsString;
        String expectedAsString;

        DOMTransformer transformer = new XHTMLBasicUnabridgedTransformer(
                new XHTMLBasicConfiguration());

        // Useful debug output
        //System.out.println("Original DOM:");
        //System.out.println(DOMUtilities.toString(dom, protocol.getCharacterEncoder()));

        transformer.transform(protocol, dom);

        // Useful debug output
        //System.out.println("Transformed DOM:");
        //System.out.println(DOMUtilities.toString(dom, protocol.getCharacterEncoder()));

        domAsString = helper.render(dom);
        expectedAsString = helper.render(expectedDom);

        assertEquals("DOM comparison failed",
                     expectedAsString,
                     domAsString);
    }
}

/*
 ===========================================================================
 Change History
 ===========================================================================
 $Log$

 30-Sep-05	9637/1	emma	VBM:2005092807 XForms in XDIME-CP (without tests)

 01-Sep-05	9375/1	geoff	VBM:2005082301 XDIMECP: clean up protocol creation

 22-Aug-05	9223/4	emma	VBM:2005080403 Remove style class from within protocols and transformers

 19-Aug-05	9289/2	emma	VBM:2005081602 Refactoring UnabridgedTransformers so they're not singletons

 21-Jun-05	8856/1	geoff	VBM:2005062005 Refactoring for XDIMECP: Generate optimised CSS for a DOM.

 05-May-05	8005/1	pduffin	VBM:2005050404 Separated DOM from within runtime into its own subsystem, move concrete DOM objects out of API, replaced with interfaces and factories, removed pooling

 08-Dec-04	6416/3	ianw	VBM:2004120703 New Build

 08-Dec-04	6416/1	ianw	VBM:2004120703 New Build

 30-Jun-04	4781/3	adrianj	VBM:2002111405 Created SMS test case and added check for null/empty mime types in protocols

 30-Jun-04	4781/1	adrianj	VBM:2002111405 VolantisProtocol.defaultMimeType() and DOMProtocol made abstract

 05-Jan-04	2380/1	allan	VBM:2004010406 Improve handling of non-well-formed XML in policy files.

 ===========================================================================
*/
