#!/bin/sh
cat >${WAS_HOME}/mps/install/jacl.properties<<-EOF
was.repository.root=${WAS_HOME}/config
server.root=${WAS_HOME}
user.install.root=${WAS_HOME}
EOF
cd ${WAS_HOME}/mps/install
${WAS_HOME}/bin/ws_ant  -f ${WAS_HOME}/mps/install/MCSMPSInstaller.xml -Dwas.platform.script.ext=.sh -DNodeName=${WAS_NODE} "$@"

#
# ===========================================================================
# Change History
# ===========================================================================
# $Log$

# 20-Dec-04	6522/1	pcameron	VBM:2004122004 New packagers for wemp

# ===========================================================================
#
