/*
This file is part of Volantis Mobility Server. 

Volantis Mobility Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Volantis Mobility Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Volantis Mobility Server.  If not, see <http://www.gnu.org/licenses/>. 
*/
package com.volantis.mcs.eclipse.builder.editors.themes;

import com.volantis.mcs.themes.StyleValue;

/**
 * A post-processing object that can be used to tidy up a parsed style value.
 *
 * <p>For example, a StyleValuePostProcessor might convert
 * {@link com.volantis.mcs.themes.StyleInvalid} objects to
 * {@link com.volantis.mcs.themes.StyleString}, for properties that have
 * the potential to be string values, but may be parsed as invalid if they
 * are not quoted.</p>.
 */
public interface StyleValuePostProcessor {
    /**
     * Post-process a style value that has been generated by the CSS parser.
     *
     * <p>Typically this method should attempt to modify
     * {@link com.volantis.mcs.themes.StyleInvalid} values in such a way that
     * the parser can identify them correctly for the relevant property type.</p>
     *
     * <p>If no additional processing is required or possible, the original
     * style value should be passed through unchanged.</p>
     *
     * @param value The value to post-process
     * @return The post-processed value, or the original value if no change was
     *         made
     */
    public StyleValue postProcess(StyleValue value);
}
/*
 ===========================================================================
 Change History
 ===========================================================================
 $Log$

 09-Nov-05	10197/2	adrianj	VBM:2005110434 Allow user-friendly entry of strings and component URIs

 ===========================================================================
*/
