/*
This file is part of Volantis Mobility Server. 

Volantis Mobility Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Volantis Mobility Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Volantis Mobility Server.  If not, see <http://www.gnu.org/licenses/>. 
*/
/* ----------------------------------------------------------------------------
 * $Header: /src/voyager/com/volantis/mcs/protocols/forms/FieldHandler.java,v 1.2 2002/03/18 12:41:18 ianw Exp $
 * ----------------------------------------------------------------------------
 * (c) Volantis Systems Ltd 2002. 
 * ----------------------------------------------------------------------------
 * Change History:
 *
 * Date         Who             Description
 * ---------    --------------- -----------------------------------------------
 * 19-Feb-02    Paul            VBM:2001100102 - Created to provide a mechanism
 *                              for resolving differences in the ways protocols
 *                              handle form parameters.
 * 18-Mar-02    Ian             VBM:2002031203 Changed log4j Category from class
                                to string.
 * ----------------------------------------------------------------------------
 */

package com.volantis.mcs.protocols.forms;

import com.volantis.mcs.context.MarinerPageContext;
import com.volantis.mcs.utilities.MarinerURL;

/**
 * This interface provides a general way for resolving differences between the
 * way different protocols handle different types of field.
 */
public interface FieldHandler {

    /**
     * Update the parameter value(s) in the url.
     * <p>
     * Implementations of this method will use the extra information provided
     * in order to work around differences in the way protocols handle different
     * types of parameter value.
     * </p>
     * <p>
     * This method should consume any of the source url parameters that it can.
     * The intention is that once all of these methods have been called for all
     * of the fields the source url will not contain any parameters which were
     * generated by these fields.
     * </p>
     *
     * @param context    The MarinerPageContext within which this is running.
     * @param descriptor The descriptor of the field.
     * @param src        The MarinerURL which contains the original values, this may
     *                   be modified by this method.
     * @param dst        The MarinerURL into which the fixed up values
     */
    public void updateParameterValue(
            MarinerPageContext context,
            FieldDescriptor descriptor,
            MarinerURL src,
            MarinerURL dst);
}

/*
 ===========================================================================
 Change History
 ===========================================================================
 $Log$

 08-Dec-04	6416/3	ianw	VBM:2004120703 New Build

 08-Dec-04	6416/1	ianw	VBM:2004120703 New Build

 23-Mar-04	3362/1	steve	VBM:2003082208 Move API doclet to Synergetics and myriads of javadoc fixes

 ===========================================================================
*/
