/*
This file is part of Volantis Mobility Server. 

Volantis Mobility Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Volantis Mobility Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Volantis Mobility Server.  If not, see <http://www.gnu.org/licenses/>. 
*/
/* ----------------------------------------------------------------------------
 * (c) Volantis Systems Ltd 2003. 
 * ----------------------------------------------------------------------------
 */
package com.volantis.mcs.integration.transcoder;

import com.volantis.mcs.context.MarinerRequestContext;
import com.volantis.mcs.integration.TranscodingException;
import com.volantis.mcs.integration.NativeURLParameterProvider;
import com.volantis.mcs.integration.TranscoderURLParameterProvider;
import com.volantis.synergetics.log.LogDispatcher;
import com.volantis.mcs.localization.LocalizationFactory;

/**
 * This specialist transcoder permits MCS to invoke the ICS transcoder in
 * native mode (where ICS accepts ICS parameters), including support for GIF
 * images.
 * <p>
 * In order for this plugin to function correctly, it requires that ICS is
 * running under JDK 1.4 with access to the Image IO Tools jar in order for
 * GIF support to function correctly.
 */
public class ICSWithGIF extends ParameterizedTranscoder {

    /**
     * Used for logging
     */
    private static final LogDispatcher logger = 
            LocalizationFactory.createLogger(ICSWithGIF.class);

    /**
     * Symbolic name for the index in a standard rule to find the target
     * encoding.
     */
    protected static final int TARGET_OFFSET = 1;

    /**
     * Symbolic name to allow meaning to be associated with a simple character
     * value. The character used to identify greyscale targets in the standard
     * rules.
     */
    protected static final char GREY = 'g';

    /**
     * Symbolic name to allow meaning to be associated with a simple character
     * value. The character used to identify GIF targets in the standard rules.
     */
    protected static final char GIF = 'g';

    /**
     * Symbolic name to allow meaning to be associated with a simple character
     * value. The character used to identify PNG targets in the standard rules.
     */
    protected static final char PNG = 'p';

    /**
     * Symbolic name to allow meaning to be associated with a simple character
     * value. The character used to identify WBMP targets in the standard rules.
     */
    protected static final char WBMP = 'w';

    /**
     * Symbolic name for the monochrome WBMP standard rule string.
     */
    protected static final String MONO_WBMP = "" + GREY + WBMP + "1";

    /**
     * Symbolic name for the monochrome GIF standard rule string.
     */
    protected static final String MONO_GIF = "" + GREY + GIF + "1";

    /**
     * Symbolic name for the greyscale 2 level GIF standard rule string.
     */
    protected static final String GREY_GIF_2 = "" + GREY + GIF + "2";

    /**
     * Initializes the new instance.
     */
    public ICSWithGIF() {
        this(NativeURLParameterProvider.SINGLETON);
    }

    /**
     * Initializes the new instance.
     * @param transcoderURLParameterProvider the TranscoderURLParameterProvider
     * that will provide the right parameter names for urls generated by this
     * transcoder.
     */
    protected ICSWithGIF(TranscoderURLParameterProvider transcoderURLParameterProvider) {
        super(transcoderURLParameterProvider);
    }


    /**
     * Avoid requesting writing of monochrome GIFs which are currently not
     * supported by ICS due to an Image IO Tools bug.
     */
    protected String ruleToBeApplied(String ruleValue,
            MarinerRequestContext context) throws TranscodingException {

        String result;

        // Because of a bug in the Image I/O Tools 1.0_01 RC jar we cannot use
        // the monochrome GIF support in ICS as it is broken. See
        // http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=5104015
        // For now we substitute a 2 level gif instead. Once this has been fixed
        // and a new Image IO Tools jar included this method may be removed.
        if (ruleValue.equals(MONO_GIF)) {
            result = GREY_GIF_2;
            if (logger.isDebugEnabled()) {
                logger.debug("Rule " + ruleValue + " has been switched to " +
                             "the alternative rule " + result);
            }

        } else {
            result = ruleValue;
        }

        return result;
    }
}

/*
 ===========================================================================
 Change History
 ===========================================================================
 $Log$

 18-Jan-05	6705/1	allan	VBM:2005011708 Remove the height from the width parameter

 08-Dec-04	6416/3	ianw	VBM:2004120703 New Build

 08-Dec-04	6416/1	ianw	VBM:2004120703 New Build

 01-Dec-04	6356/1	geoff	VBM:2004112205 MCS Transcoder Transforce plugin

 29-Nov-04	6232/4	doug	VBM:2004111702 Refactored Logging framework

 04-Nov-04	6109/2	philws	VBM:2004072013 Update the convertImageURLTo... pipeline processes to utilize the current pluggable asset transcoder's parameter names

 21-Sep-04	5559/1	geoff	VBM:2004091506 Support GIF as transcoded image type in MCS and ICS

 29-Jul-04	4991/3	byron	VBM:2004070510 VTS classes need renaming in MCS to ICS

 30-Apr-04	4128/1	ianw	VBM:2004042905 Changed v.maxsize to v.maxSize

 19-Feb-04	2789/3	tony	VBM:2004012601 refactored localised logging to synergetics

 12-Feb-04	2789/1	tony	VBM:2004012601 Localised logging (and exceptions)

 05-Dec-03	2075/1	mat	VBM:2003120106 Rename Device and add a public Device Interface

 29-Sep-03	1454/3	philws	VBM:2003092401 Minor updates requested in the code review

 26-Sep-03	1454/1	philws	VBM:2003092401 Provide asset transcoder plugin API and configuration-selectable standard implementations

 ===========================================================================
*/
