/*
This file is part of Volantis Mobility Server. 

Volantis Mobility Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Volantis Mobility Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Volantis Mobility Server.  If not, see <http://www.gnu.org/licenses/>. 
*/
/* ----------------------------------------------------------------------------
 * This code was automatically generated by PropertyValueLookupUtilities
 * on 3/14/08 7:12 PM
 *
 * YOU MUST NOT MODIFY THIS FILE
 * ----------------------------------------------------------------------------
 */

package com.volantis.mcs.assets;

import java.util.HashMap;
import java.util.Map;

public class ChartAssetUtilities {

  /**
   * An array of the allowable values for the chart asset type.
   */
  private static Object [] typeArray;

  static {
    Object internal;
    String external;

    typeArray = new String [] {
      ChartAsset.BAR_CHART,
      ChartAsset.COLUMN_CHART,
      ChartAsset.LEGEND_CHART,
      ChartAsset.LINE_CHART,
      ChartAsset.PIE_CHART,
    };
  }

  public static Object [] getTypeArray () {
    return typeArray;
  }
}
