<?xml version="1.0" encoding="UTF-8"?>  
	<div 
		xmlns="http://www.w3.org/2002/06/xhtml2" 
		xmlns:xf="http://www.w3.org/2002/xforms" style="mcs-layout: 'layouts/2x2.mlyt'">
		
  	<xf:input ref="login" style="mcs-container: 'top-right'">
    	<xf:label style="mcs-container: 'top-left'">Login</xf:label>
    </xf:input>
    
    <xf:input ref="password" style="mcs-container: 'bottom-right'">
    	<xf:label style="mcs-container: 'bottom-left'">Password</xf:label>
    </xf:input>
  </div>
