<!--
This file is part of Volantis Mobility Server. 

Volantis Mobility Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Volantis Mobility Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Volantis Mobility Server.  If not, see <http://www.gnu.org/licenses/>. 
-->
<!--  *************************************************************************
        (c) Volantis Systems Ltd 2001. 
      *************************************************************************
        Revision Info
        Name    Date            Comment
        AFP     31/10/02     	 Created this file

      *************************************************************************
-->


<%@ include file="Volantis-mcs.jsp" %>

<vt:canvas theme="tt_lineheight" layoutName="standard" pageTitle="Themes: Box" >

<vt:pane name="main2">
filename: tt_lineheight.jsp<vt:br/><vt:br/>
theme: tt_lineheight<vt:br/>
layout: standard<vt:br/>
Devices: All

<vt:br/><vt:br/>
<vt:p>
<vt:a href="index.jsp">Main Index</vt:a> =>
<vt:a href="tt_themes.jsp">Themes</vt:a> =>
<vt:a href="tt_themes_box.jsp">Box</vt:a> =>
tt_margins.jsp
</vt:p>

This page tests the line height property. This can be found in the box Tab of the Mariner GUI in the style properties window. <vt:br/><vt:br/>
Test:<vt:br/>
p{border:1.0px #a0a solid;font-size:10.0pt}<vt:br/>
p.lineheight1{line-height:2.5}<vt:br/>
p.lineheight2{line-height:170.0%}<vt:br/>
p.lineheight3{line-height:normal}<vt:br/>
div{border:1.0px #f00 solid;font-size:14.0pt}<vt:br/>
div.lineheight1{line-height:1.8em}<vt:br/>
div.lineheight2{line-height:60.0px}<vt:br/>
<vt:br/>
Expected Results: <vt:br/>
css: as above<vt:br/>
Wap TV:<vt:br/>
<vt:br/>

<vt:p>This paragraph has no styleClass. If the property is set on a block-level element whose content is composed of inline-level elements, it specifies the minimal height of each generated inline box. If the property is set on an inline-level element, it specifies the exact height of each box generated by the element. (Except for inline replaced elements, where the height of the box is given by the 'height' property.)</vt:p>

<vt:p styleClass="lineheight1">This paragraph has styleClass=lineheight1. If the property is set on a block-level element whose content is composed of inline-level elements, it specifies the minimal height of each generated inline box. If the property is set on an inline-level element, it specifies the exact height of each box generated by the element. (Except for inline replaced elements, where the height of the box is given by the 'height' property.)</vt:p>

<vt:p styleClass="lineheight2">This paragraph tag has styleClass=lineheight2.If the property is set on a block-level element whose content is composed of inline-level elements, it specifies the minimal height of each generated inline box. If the property is set on an inline-level element, it specifies the exact height of each box generated by the element. (Except for inline replaced elements, where the height of the box is given by the 'height' property.)</vt:p>

<vt:p styleClass="lineheight3">This paragraph tag has styleClass=lineheight3.If the property is set on a block-level element whose content is composed of inline-level elements, it specifies the minimal height of each generated inline box. If the property is set on an inline-level element, it specifies the exact height of each box generated by the element. (Except for inline replaced elements, where the height of the box is given by the 'height' property.)</vt:p>

<vt:div styleClass="lineheight1">This div tag has styleClass=lineheight1.If the property is set on a block-level element whose content is composed of inline-level elements, it specifies the minimal height of each generated inline box. If the property is set on an inline-level element, it specifies the exact height of each box generated by the element. (Except for inline replaced elements, where the height of the box is given by the 'height' property.)</vt:div>

<vt:br/>

<vt:div styleClass="lineheight2">This div tag has styleClass=lineheight2.If the property is set on a block-level element whose content is composed of inline-level elements, it specifies the minimal height of each generated inline box. If the property is set on an inline-level element, it specifies the exact height of each box generated by the element. (Except for inline replaced elements, where the height of the box is given by the 'height' property.)</vt:div>

<vt:br/>
<vt:p>
<vt:a href="index.jsp">Main Index</vt:a> =>
<vt:a href="tt_themes.jsp">Themes</vt:a> =>
<vt:a href="tt_themes_box.jsp">Box</vt:a> =>
tt_margins.jsp
</vt:p>


</vt:pane>

</vt:canvas>

