/*
This file is part of Volantis Mobility Server. 

Volantis Mobility Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Volantis Mobility Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Volantis Mobility Server.  If not, see <http://www.gnu.org/licenses/>. 
*/
/* ----------------------------------------------------------------------------
 * This code was automatically generated by com.volantis.mcs.build.objects.CommonObjectsCodeGenerator
 * on 3/14/08 7:12 PM
 *
 * YOU MUST NOT MODIFY THIS FILE
 * ----------------------------------------------------------------------------
 */

package com.volantis.mcs.assets;

import com.volantis.mcs.objects.AbstractRepositoryObjectIdentity;

import com.volantis.mcs.project.Project;

/**
 * Encapsulates those properties of a DynamicVisualAsset which uniquely
 * identify it.
 * @volantis-api-include-in PublicAPI
 * @volantis-api-include-in ProfessionalServicesAPI
 * @volantis-api-include-in InternalAPI
 * @deprecated See {@link com.volantis.mcs.policies}.
 * This was deprecated in version 3.5.1.
 */
public class DynamicVisualAssetIdentity
  extends AbstractRepositoryObjectIdentity {

  /**
   * The encoding of this asset
   */
  private int encoding;

  /**
   * The width of the asset in pixels
   */
  private int pixelsX;

  /**
   * The height of the asset in pixels
   */
  private int pixelsY;

  /**
   * Create a new <code>DynamicVisualAssetIdentity</code>.
   * @param project  The project used with this object.   A null value is
   * possible if it
   * has not been set.
   * @param name  The name of the object.
   */
  public DynamicVisualAssetIdentity (Project project,
                                     String name,
                                     int encoding,
                                     int pixelsX,
                                     int pixelsY) {
    super(project, name);

    this.encoding = encoding;
    this.pixelsX = pixelsX;
    this.pixelsY = pixelsY;
  }

  /**
   * Create a new <code>DynamicVisualAssetIdentity</code>.
   * @param name  The name of the object.
   */
  public DynamicVisualAssetIdentity (String name,
                                     int encoding,
                                     int pixelsX,
                                     int pixelsY) {
    super(null, name);

    this.encoding = encoding;
    this.pixelsX = pixelsX;
    this.pixelsY = pixelsY;
  }

  /**
   * Get the value of encoding.
   * @return value of encoding.
   */
  public int getEncoding () {
    return encoding;
  }

  /**
   * Get the width of the asset in pixels
   * @return The width of the asset in pixels
   */
  public int getPixelsX () {
    return pixelsX;
  }

  /**
   * Get the height of the asset in pixels
   * @return The height of the asset in pixels
   */
  public int getPixelsY () {
    return pixelsY;
  }

  // Javadoc inherited from super class.
  public Class getObjectClass () {
    return DynamicVisualAsset.class;
  }

  // Javadoc inherited from super class.
  public boolean equals (Object object) {

    // Call the super class to check whether this object and the other object
    // are of the same type and have the same name.
    if (!super.equals (object)) {
      return false;
    }

    DynamicVisualAssetIdentity identity = (DynamicVisualAssetIdentity) object;
    return encoding == identity.encoding
      && pixelsX == identity.pixelsX
      && pixelsY == identity.pixelsY;
  }

  // Javadoc inherited from super class.
  public int hashCode () {
    return super.hashCode ()
      + encoding

      + pixelsX

      + pixelsY
;
  }

  // Javadoc inherited from super class.
  public int compareTo (Object object) {

    // Call the super class to check whether this object and the other object
    // are of the same type and have the same name.
    int result;
    if ((result = super.compareTo (object)) != 0) {
      return result;
    }

    DynamicVisualAssetIdentity identity = (DynamicVisualAssetIdentity) object;

    // Compare the encoding
    if ((result = compare (encoding, identity.encoding)) != 0) {
      return result;
    }

    // Compare the pixelsX
    if ((result = compare (pixelsX, identity.pixelsX)) != 0) {
      return result;
    }

    // Compare the pixelsY
    if ((result = compare (pixelsY, identity.pixelsY)) != 0) {
      return result;
    }

    // The identities are equal.
    return 0;
  }

  // Javadoc inherited from super class.
  protected String paramString () {
    return super.paramString ()
      + ", encoding=" + encoding
      + ", pixelsX=" + pixelsX
      + ", pixelsY=" + pixelsY;
  }
}
