/*
This file is part of Volantis Mobility Server. 

Volantis Mobility Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Volantis Mobility Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Volantis Mobility Server.  If not, see <http://www.gnu.org/licenses/>. 
*/
/* ----------------------------------------------------------------------------
 * This code was automatically generated by PropertyValueLookupUtilities
 * on 3/14/08 7:12 PM
 *
 * YOU MUST NOT MODIFY THIS FILE
 * ----------------------------------------------------------------------------
 */

package com.volantis.mcs.assets;

import java.util.HashMap;
import java.util.Map;

public class DynamicVisualAssetUtilities {

  /**
   * An array of the allowable values for the dynamic visual asset encoding.
   */
  private static Object [] encodingArray;

  /**
   * A bidirectional map between internal and external representations of the
   * dynamic visual asset encoding.
   */
  private static Map encodingMap;

  static {
    Object internal;
    String external;

    encodingArray = new Integer [] {
      new Integer (DynamicVisualAsset.ANIMATED_GIF),
      new Integer (DynamicVisualAsset.MPEG1),
      new Integer (DynamicVisualAsset.MPEG4),
      new Integer (DynamicVisualAsset.WINDOWS_MEDIA_VIDEO),
      new Integer (DynamicVisualAsset.MACROMEDIA_FLASH),
      new Integer (DynamicVisualAsset.MACROMEDIA_SHOCKWAVE),
      new Integer (DynamicVisualAsset.QUICKTIME_VIDEO),
      new Integer (DynamicVisualAsset.REAL_VIDEO),
      new Integer (DynamicVisualAsset.TV),
      new Integer (DynamicVisualAsset.THREE_GPP),
    };

    encodingMap = new HashMap ();

    external = "gif";
    encodingMap.put (encodingArray [0], external);
    encodingMap.put (external, encodingArray [0]);

    external = "mpeg1";
    encodingMap.put (encodingArray [1], external);
    encodingMap.put (external, encodingArray [1]);

    external = "mpeg4";
    encodingMap.put (encodingArray [2], external);
    encodingMap.put (external, encodingArray [2]);

    external = "windowsVideo";
    encodingMap.put (encodingArray [3], external);
    encodingMap.put (external, encodingArray [3]);

    external = "flash";
    encodingMap.put (encodingArray [4], external);
    encodingMap.put (external, encodingArray [4]);

    external = "shock";
    encodingMap.put (encodingArray [5], external);
    encodingMap.put (external, encodingArray [5]);

    external = "quickTime";
    encodingMap.put (encodingArray [6], external);
    encodingMap.put (external, encodingArray [6]);

    external = "realVideo";
    encodingMap.put (encodingArray [7], external);
    encodingMap.put (external, encodingArray [7]);

    external = "tv";
    encodingMap.put (encodingArray [8], external);
    encodingMap.put (external, encodingArray [8]);

    external = "3gpp";
    encodingMap.put (encodingArray [9], external);
    encodingMap.put (external, encodingArray [9]);
  }

  public static Object [] getEncodingArray () {
    return encodingArray;
  }

  public static Map getEncodingMap () {
    return encodingMap;
  }
}
