/*
This file is part of Volantis Mobility Server. 

Volantis Mobility Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Volantis Mobility Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Volantis Mobility Server.  If not, see <http://www.gnu.org/licenses/>. 
*/
/* ----------------------------------------------------------------------------
 * This code was automatically generated by com.volantis.mcs.build.objects.CommonObjectsCodeGenerator
 * on 3/14/08 7:12 PM
 *
 * YOU MUST NOT MODIFY THIS FILE
 * ----------------------------------------------------------------------------
 */

package com.volantis.mcs.assets;

import com.volantis.mcs.objects.AbstractRepositoryObjectIdentity;
import com.volantis.mcs.objects.RepositoryObjectDeviceIdentity;

import com.volantis.mcs.project.Project;

/**
 * Encapsulates those properties of a LinkAsset which uniquely identify it.
 * @volantis-api-include-in PublicAPI
 * @volantis-api-include-in ProfessionalServicesAPI
 * @volantis-api-include-in InternalAPI
 * @deprecated See {@link com.volantis.mcs.policies}.
 * This was deprecated in version 3.5.1.
 */
public class LinkAssetIdentity
  extends AbstractRepositoryObjectIdentity
  implements RepositoryObjectDeviceIdentity {

  /**
   * The device name associated with the LinkAsset
   */
  private String deviceName;

  /**
   * Create a new <code>LinkAssetIdentity</code>.
   * @param project  The project used with this object.   A null value is
   * possible if it
   * has not been set.
   * @param name  The name of the object.
   */
  public LinkAssetIdentity (Project project,
                            String name,
                            String deviceName) {
    super(project, name);

    this.deviceName = deviceName;
  }

  /**
   * Create a new <code>LinkAssetIdentity</code>.
   * @param name  The name of the object.
   */
  public LinkAssetIdentity (String name,
                            String deviceName) {
    super(null, name);

    this.deviceName = deviceName;
  }

  /**
   * Access method for the deviceName property.
   * @return   the current value of the deviceName property
   */
  public String getDeviceName () {
    return deviceName;
  }

  // Javadoc inherited from super class.
  public Class getObjectClass () {
    return LinkAsset.class;
  }

  // Javadoc inherited from super class.
  public boolean equals (Object object) {

    // Call the super class to check whether this object and the other object
    // are of the same type and have the same name.
    if (!super.equals (object)) {
      return false;
    }

    LinkAssetIdentity identity = (LinkAssetIdentity) object;
    return equals (deviceName, identity.deviceName);
  }

  // Javadoc inherited from super class.
  public int hashCode () {
    return super.hashCode ()
      + hashCode (deviceName)
;
  }

  // Javadoc inherited from super class.
  public int compareTo (Object object) {

    // Call the super class to check whether this object and the other object
    // are of the same type and have the same name.
    int result;
    if ((result = super.compareTo (object)) != 0) {
      return result;
    }

    LinkAssetIdentity identity = (LinkAssetIdentity) object;

    // Compare the deviceName
    if ((result = compare (deviceName, identity.deviceName)) != 0) {
      return result;
    }

    // The identities are equal.
    return 0;
  }

  // Javadoc inherited from super class.
  protected String paramString () {
    return super.paramString ()
      + ", deviceName=" + deviceName;
  }
}
