ALTER TABLE VMMENUPROPERTIES add MRNR_MENU_IMG_STYLE_SYNTAX numeric(3) DEFAULT -1 NOT NULL;
ALTER TABLE VMMENUPROPERTIES add MRNR_MENU_IMG_STYLE_PRIORITY numeric(3) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPERTIES add MRNR_MENU_IMG_STYLE_KEYWD numeric(9) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPERTIES add MRNR_MITEM_ACT_AREA_SYNTAX numeric(3) DEFAULT -1 NOT NULL;
ALTER TABLE VMMENUPROPERTIES add MRNR_MITEM_ACT_AREA_PRIORITY numeric(3) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPERTIES add MRNR_MITEM_ACT_AREA_KEYWD numeric(9) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPERTIES add MRNR_MITEM_ITR_ALLC_SYNTAX numeric(3) DEFAULT -1 NOT NULL;
ALTER TABLE VMMENUPROPERTIES add MRNR_MITEM_ITR_ALLC_PRIORITY numeric(3) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPERTIES add MRNR_MITEM_ITR_ALLC_KEYWD numeric(9) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPERTIES add MRNR_MITEM_ORDER_SYNTAX numeric(3) DEFAULT -1 NOT NULL;
ALTER TABLE VMMENUPROPERTIES add MRNR_MITEM_ORDER_PRIORITY numeric(3) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPERTIES add MRNR_MITEM_ORDER_KEYWD numeric(9) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPERTIES add MRNR_MITEM_ORN_SYNTAX numeric(3) DEFAULT -1 NOT NULL;
ALTER TABLE VMMENUPROPERTIES add MRNR_MITEM_ORN_PRIORITY numeric(3) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPERTIES add MRNR_MITEM_ORN_KEYWD numeric(9) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPERTIES add MRNR_MENU_STYLE_SYNTAX numeric(3) DEFAULT -1 NOT NULL;
ALTER TABLE VMMENUPROPERTIES add MRNR_MENU_STYLE_PRIORITY numeric(3) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPERTIES add MRNR_MENU_STYLE_KEYWD numeric(9) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPERTIES add MRNR_MENU_TXT_STYLE_SYNTAX numeric(3) DEFAULT -1 NOT NULL;
ALTER TABLE VMMENUPROPERTIES add MRNR_MENU_TXT_STYLE_PRIORITY numeric(3) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPERTIES add MRNR_MENU_TXT_STYLE_KEYWD numeric(9) DEFAULT 0 NOT NULL;

commit;

ALTER TABLE VSMENUPROPERTIES add MRNR_MENU_IMG_STYLE_SYNTAX numeric(3) DEFAULT -1 NOT NULL;
ALTER TABLE VSMENUPROPERTIES add MRNR_MENU_IMG_STYLE_PRIORITY numeric(3) DEFAULT 0 NOT NULL;
ALTER TABLE VSMENUPROPERTIES add MRNR_MENU_IMG_STYLE_KEYWD numeric(9) DEFAULT 0 NOT NULL;
ALTER TABLE VSMENUPROPERTIES add MRNR_MITEM_ACT_AREA_SYNTAX numeric(3) DEFAULT -1 NOT NULL;
ALTER TABLE VSMENUPROPERTIES add MRNR_MITEM_ACT_AREA_PRIORITY numeric(3) DEFAULT 0 NOT NULL;
ALTER TABLE VSMENUPROPERTIES add MRNR_MITEM_ACT_AREA_KEYWD numeric(9) DEFAULT 0 NOT NULL;
ALTER TABLE VSMENUPROPERTIES add MRNR_MITEM_ITR_ALLC_SYNTAX numeric(3) DEFAULT -1 NOT NULL;
ALTER TABLE VSMENUPROPERTIES add MRNR_MITEM_ITR_ALLC_PRIORITY numeric(3) DEFAULT 0 NOT NULL;
ALTER TABLE VSMENUPROPERTIES add MRNR_MITEM_ITR_ALLC_KEYWD numeric(9) DEFAULT 0 NOT NULL;
ALTER TABLE VSMENUPROPERTIES add MRNR_MITEM_ORDER_SYNTAX numeric(3) DEFAULT -1 NOT NULL;
ALTER TABLE VSMENUPROPERTIES add MRNR_MITEM_ORDER_PRIORITY numeric(3) DEFAULT 0 NOT NULL;
ALTER TABLE VSMENUPROPERTIES add MRNR_MITEM_ORDER_KEYWD numeric(9) DEFAULT 0 NOT NULL;
ALTER TABLE VSMENUPROPERTIES add MRNR_MITEM_ORN_SYNTAX numeric(3) DEFAULT -1 NOT NULL;
ALTER TABLE VSMENUPROPERTIES add MRNR_MITEM_ORN_PRIORITY numeric(3) DEFAULT 0 NOT NULL;
ALTER TABLE VSMENUPROPERTIES add MRNR_MITEM_ORN_KEYWD numeric(9) DEFAULT 0 NOT NULL;
ALTER TABLE VSMENUPROPERTIES add MRNR_MENU_STYLE_SYNTAX numeric(3) DEFAULT -1 NOT NULL;
ALTER TABLE VSMENUPROPERTIES add MRNR_MENU_STYLE_PRIORITY numeric(3) DEFAULT 0 NOT NULL;
ALTER TABLE VSMENUPROPERTIES add MRNR_MENU_STYLE_KEYWD numeric(9) DEFAULT 0 NOT NULL;
ALTER TABLE VSMENUPROPERTIES add MRNR_MENU_TXT_STYLE_SYNTAX numeric(3) DEFAULT -1 NOT NULL;
ALTER TABLE VSMENUPROPERTIES add MRNR_MENU_TXT_STYLE_PRIORITY numeric(3) DEFAULT 0 NOT NULL;
ALTER TABLE VSMENUPROPERTIES add MRNR_MENU_TXT_STYLE_KEYWD numeric(9) DEFAULT 0 NOT NULL;

commit;

ALTER TABLE VMMENUPROPS add MRNR_MENU_IMG_STYLE_SYNTAX numeric(3) DEFAULT -1 NOT NULL;
ALTER TABLE VMMENUPROPS add MRNR_MENU_IMG_STYLE_PRIORITY numeric(3) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPS add MRNR_MENU_IMG_STYLE_KEYWD numeric(9) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPS add MRNR_MITEM_ACT_AREA_SYNTAX numeric(3) DEFAULT -1 NOT NULL;
ALTER TABLE VMMENUPROPS add MRNR_MITEM_ACT_AREA_PRIORITY numeric(3) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPS add MRNR_MITEM_ACT_AREA_KEYWD numeric(9) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPS add MRNR_MITEM_ITR_ALLC_SYNTAX numeric(3) DEFAULT -1 NOT NULL;
ALTER TABLE VMMENUPROPS add MRNR_MITEM_ITR_ALLC_PRIORITY numeric(3) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPS add MRNR_MITEM_ITR_ALLC_KEYWD numeric(9) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPS add MRNR_MITEM_ORDER_SYNTAX numeric(3) DEFAULT -1 NOT NULL;
ALTER TABLE VMMENUPROPS add MRNR_MITEM_ORDER_PRIORITY numeric(3) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPS add MRNR_MITEM_ORDER_KEYWD numeric(9) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPS add MRNR_MITEM_ORN_SYNTAX numeric(3) DEFAULT -1 NOT NULL;
ALTER TABLE VMMENUPROPS add MRNR_MITEM_ORN_PRIORITY numeric(3) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPS add MRNR_MITEM_ORN_KEYWD numeric(9) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPS add MRNR_MENU_STYLE_SYNTAX numeric(3) DEFAULT -1 NOT NULL;
ALTER TABLE VMMENUPROPS add MRNR_MENU_STYLE_PRIORITY numeric(3) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPS add MRNR_MENU_STYLE_KEYWD numeric(9) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPS add MRNR_MENU_TXT_STYLE_SYNTAX numeric(3) DEFAULT -1 NOT NULL;
ALTER TABLE VMMENUPROPS add MRNR_MENU_TXT_STYLE_PRIORITY numeric(3) DEFAULT 0 NOT NULL;
ALTER TABLE VMMENUPROPS add MRNR_MENU_TXT_STYLE_KEYWD numeric(9) DEFAULT 0 NOT NULL;

commit;

REM
REM ===========================================================================
REM Change History
REM ===========================================================================
REM $Log$

REM 17-May-04	4432/1	byron	VBM:2004051701 SQL script has missing add keyword

REM 28-Apr-04	3937/1	byron	VBM:2004032308 Enhance Menu Support: Theme Changes: Update renderers and parsers

REM ===========================================================================
REM
