#! /bin/bash

if [ -z "$GBUILD_LOCATION" ]; then 
  echo "Please set GBUILD_LOCATION environment variable"
  exit 0
fi
if [ -z "$JAVA_HOME" ]; then 
  echo "Please set JAVA_HOME environment variable"
  exit 0
fi

BUILD_VERSION=0.8
BUILD_MODE=offline

echo 
echo "========================================"
echo "  Build Environment"
echo "========================================"
echo
echo "GBuild Version: $BUILD_VERSION"
echo "Bootstrap location: $GBUILD_LOCATION"
echo
$JAVA_HOME/bin/java -version
echo

CP=""
SEP=""
for JAR in $GBUILD_LOCATION/lib/*.jar
do
    CP="$CP$SEP$JAR"
    SEP=":"
done
$JAVA_HOME/bin/java -Xmx256M -XX:MaxPermSize=96M $GBUILD_JAVA_OPTS -cp "$CP" "-Dgbuild.version=$BUILD_VERSION" "-Dgbuild.mode=$BUILD_MODE" "-Dgbuild.install.dir=$GBUILD_LOCATION/lib" org.grease.cli.Main ${1+"$@"}
