/*
This file is part of Volantis Mobility Server. 

Volantis Mobility Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Volantis Mobility Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Volantis Mobility Server.  If not, see <http://www.gnu.org/licenses/>. 
*/
/* ----------------------------------------------------------------------------
 * (c) Volantis Systems Ltd 2004. 
 * ----------------------------------------------------------------------------
 */
package com.volantis.mcs.protocols.menu.model;

import com.volantis.styling.Styles;

/**
 * This interface provides access to the details of the PAPI element (i.e. type,
 * style class and ID) which is associated with the menu entity that is using
 * an instance of an implementation of this class.
 * <p/>
 * It also provides access to a {@link Styles} instance populated with the
 * stylistic values which are applicable to the PAPI element associated with
 * the menu entity that is using this class.
 *
 * @mock.generate
 */
public interface ElementDetails {
    /**
     * Returns the name of the PAPI element which is associated with
     * the menu entity that is using this class.
     *
     * @return the element name associated with this entity. May be null.
     */
    String getElementName();

    /**
     * Returns the ID of the PAPI element which is associated with
     * the menu entity that is using this class.
     *
     * @return the ID for this entity. May be null
     */
    String getId();

    /**
     * Returns the style property values that are applicable to the PAPI
     * element which is associated with the menu entity that is using this
     * class (generated by the Styling Engine).
     *
     * @return the styles for this entity. Will not be null
     */
    Styles getStyles();
}

/*
 ===========================================================================
 Change History
 ===========================================================================
 $Log$

 30-Aug-05	9353/1	pduffin	VBM:2005081912 Removed style class from MCS Attributes

 30-Jun-05	8888/5	emma	VBM:2005062405 Annotate DOM elements generated from menu model classes with styles

 27-Jun-05	8888/3	emma	VBM:2005062405 Annotate DOM elements generated from menu model classes with styles

 20-Jun-05	8483/1	emma	VBM:2005052410 Migrate styling to use the new styling support framework (still using CSSEmulator to style underneath)

 08-Dec-04	6416/3	ianw	VBM:2004120703 New Build

 08-Dec-04	6416/1	ianw	VBM:2004120703 New Build

 13-May-04	4315/1	geoff	VBM:2004051204 Enhance Menu Support: WML Dissection: Integration

 03-Mar-04	3288/1	philws	VBM:2004022702 Add Menu Model API

 ===========================================================================
*/
